name       : gsmartcontrol
version    : 1.1.3
release    : 8
source     :
    - https://netcologne.dl.sourceforge.net/project/gsmartcontrol/1.1.3/gsmartcontrol-1.1.3.tar.bz2 : b64f62cffa4430a90b6d06cd52ebadd5bcf39d548df581e67dfb275a673b12a9
license    :
    - BSD-3-Clause
    - BSL-1.0
    - GPL-2.0-or-later
    - MIT
    - Unlicense
    - Zlib
component  : system.utils
summary    : Hard disk drive and SSD health inspection tool
description: |
    GSmartControl is a graphical user interface for smartctl (from smartmontools package), which is a tool for querying and controlling SMART (Self-Monitoring, Analysis, and Reporting Technology) data on modern hard disk and solid-state drives. It allows you to inspect the drive's SMART data to determine its health, as well as run various tests on it.
builddeps  :
    - pkgconfig(gtkmm-3.0)
    - pkgconfig(libpcrecpp)
rundeps    :
    - smartmontools
setup      : |
    %patch -p1 < $pkgfiles/0001-Remove-xterm-as-a-dependency.patch
    %configure
build      : |
    %make
install    : |
    %make_install
